speakers:
  outputs:
    - << downstairs >>
    - one
    - two
    - three
    - four
    - five
    - << slide >>
    - six
    - seven
    - << upstairs >>
    - eight
    - nine
    - ten
    - eleven
    - << props >>
    - twelve
    - thirteen
    - fourteen
    - fifteen
    - sixteen
  groups: !!omap
    - downstairs: [one, two, three, four, five]
    - ramp: [six, seven]
    - upstairs: [eight, nine, ten, eleven]
    - soundtrack: [downstairs, upstairs, ramp]
    - foo: [two, four, six, eight, ten, twelve]
controls:
  imgclues:
    type: clues
  sounds:
    type: sounds
    soundtrack:
      - name: begining
        filename: main.ogg
        speakers: soundtrack
      - name: middle
        filename: second.ogg
        speakers: soundtrack
      - name: end
        filename: soundtrack.ogg
        speakers: soundtrack
      - name: begining
        filename: main.ogg
        speakers: soundtrack
      - name: endend
        filename: soundtrack2.ogg
        speakers: [one, 2, 3, 5]
    buttons:
      - name: start soundtrack
        topic: soundtrack/start
        data: ""
        description: start the soundtrack duh
      - name: skip next
        topic: soundtrack/next
        data: ""
        description: next song
  fire:
    type: lighting
    buttons:
      - name: lights on
        topic: fire/control
        data: "on"
        description: turn the fire on
      - name: lights off
        topic: fire/control
        data: "off"
        description: turn the fire off
  lights:
    buttons:
      - name: lights on
        topic: lights/control
        data: "on"
        description: turn the main lights on
      - name: lights off
        topic: lights/control
        data: "off"
        description: turn the main lights off
      - name: flame on
        topic: lights/controljson
        data: '{"create":[{"name":"fire","strip":0,"start":32,"end":64,"palette":"TODO"}]}'
        description: start the fire
  sand:
    buttons:
      - name: answer
        topic: sand/overide
        data: '{30:[1,1,1,1,240,90,150,210]}'
        description: force correct
      - name: ez on
        topic: sand/ez
        data: 'on'
      - name: reset
        topic: sand/reset
        data: ''
  lasors:
    buttons:
      - name: arm
        topic: laser1/control
        data: '{"armed":true}'
      - name: force
        topic: laser1/control
        data: '{"forced":true}'
      - name: reset
        topic: laser1/control
        data: '{"forced":false,"armed":false}'
  relay:
    type: relayboard
    topic-header: relay
    number: 16
    relays: !!omap
      - fire: the fire pit in the middle of the room!
      - slide door: allows access to the slide
      - cupboard: opens the cupboard!
      - hidden brick: release the brick
      - puzzle 1: unnamed puzzle
      - main teleporter: pew
      - mouth: yawn
      - bees: not the beads
      - backup generator: reroute the power through the secondary systems
      - escape door: let them escape
      - smoke: blaze it
      - tazers: taze it
      - lasers: laze it
      - tigers: die
      - buzzers: baze it
      - example: foo
    buttons:
      - name: do stuff
        description: do the thing
        code: "alert('I am an alert box!');"
      - name: do more stuff
        description: do the thing
        code: >
          if (confirm("Press a button!")) {
          alert("You pressed OK!");
          } else {
          alert("You pressed Cancel!");
          }